### ISSUE TITLE
Sony Bravia Error 714

### ISSUE THREAD

**Issue by wallydz** [thibauts/node-upnp-mediarenderer-client#11]
Error {stack: "Error: Action SetAVTransportURI failed (714)↵    a…16)↵    at process._tickCallback (node.js:534:11)", code: "EUPNP", statusCode: 500, errorCode: "714", message: "Action SetAVTransportURI failed (714)"…}
code: "EUPNP"
errorCode: "714"
message: "Action SetAVTransportURI failed (714)"
stack: "Error: Action SetAVTransportURI failed (714)↵    at IncomingMessage.eval (/Applications/Popcorn-Time copy.app/Contents/Resources/app.nw/node_modules/upnp-mediarenderer-client/node_modules/upnp-device-client/index.js:128:21)↵    at IncomingMessage.EventEmitter.emit (events.js:120:20)↵    at eval (_stream_readable.js:896:16)↵    at process._tickCallback (node.js:534:11)"
statusCode: 500
__proto__: d
 "Error: Action SetAVTransportURI failed (714)
    at IncomingMessage.eval (/Applications/Popcorn-Time copy.app/Contents/Resources/app.nw/node_modules/upnp-mediarenderer-client/node_modules/upnp-device-client/index.js:128:21)
    at IncomingMessage.EventEmitter.emit (events.js:120:20)
    at eval (_stream_readable.js:896:16)
    at process._tickCallback (node.js:534:11)" app.js:452
(anonymous function) app.js:452
EventEmitter.emit events.js:120
process._fatalException node.js:164
Uncaught Error: Action SetAVTransportURI failed (714) dlna.js:34
(anonymous function) dlna.js:34
(anonymous function) /Applications/Po

**Comment by dombesz** [comment]
+1 I can help with debugging, I have this error on my Bravia.

**Comment by thibauts** [comment]
Awesome :)

Can you gist this ?

```javascript
client.getSupportedProtocols(function(err, protocols) {
  if(err) throw err;
  console.log(JSON.stringify(protocols, null, 2));
});
```

**Comment by dombesz** [comment]
Sure!

    [
      { "protocol": "http-get", "network": "*", "contentFormat": "image/jpeg", "additionalInfo": "DLNA.ORG_PN=JPEG_SM;DLNA.ORG_FLAGS=8cf00000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "image/jpeg", "additionalInfo": "DLNA.ORG_PN=JPEG_MED;DLNA.ORG_FLAGS=8cf00000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "image/jpeg", "additionalInfo": "DLNA.ORG_PN=JPEG_LRG;DLNA.ORG_FLAGS=8cf00000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "audio/mpeg", "additionalInfo": "DLNA.ORG_PN=MP3;DLNA.ORG_FLAGS=8d700000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "audio/L16", "additionalInfo": "DLNA.ORG_PN=LPCM;DLNA.ORG_FLAGS=8d700000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "video/mpeg", "additionalInfo": "DLNA.ORG_PN=AVC_TS_HD_24_AC3_ISO;SONY.COM_PN=AVC_TS_HD_24_AC3_ISO;DLNA.ORG_FLAGS=8d700000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "video/vnd.dlna.mpeg-tts", "additionalInfo": "DLNA.ORG_PN=AVC_TS_HD_24_AC3;SONY.COM_PN=AVC_TS_HD_24_AC3;DLNA.ORG_FLAGS=8d700000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "video/vnd.dlna.mpeg-tts", "additionalInfo": "DLNA.ORG_PN=AVC_TS_HD_24_AC3_T;SONY.COM_PN=AVC_TS_HD_24_AC3_T;DLNA.ORG_FLAGS=8d700000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "video/vnd.dlna.mpeg-tts", "additionalInfo": "DLNA.ORG_PN=MPEG_PS_PAL;DLNA.ORG_FLAGS=8d700000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "video/vnd.dlna.mpeg-tts", "additionalInfo": "DLNA.ORG_PN=MPEG_PS_NTSC;DLNA.ORG_FLAGS=8d700000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "video/vnd.dlna.mpeg-tts", "additionalInfo": "DLNA.ORG_PN=MPEG_TS_SD_50_L2_T;DLNA.ORG_FLAGS=8d700000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "video/vnd.dlna.mpeg-tts", "additionalInfo": "DLNA.ORG_PN=MPEG_TS_SD_60_L2_T;DLNA.ORG_FLAGS=8d700000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "video/mpeg", "additionalInfo": "DLNA.ORG_PN=MPEG_TS_SD_EU_ISO;DLNA.ORG_FLAGS=8d700000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "video/vnd.dlna.mpeg-tts", "additionalInfo": "DLNA.ORG_PN=MPEG_TS_SD_EU;DLNA.ORG_FLAGS=8d700000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "video/vnd.dlna.mpeg-tts", "additionalInfo": "DLNA.ORG_PN=MPEG_TS_SD_EU_T;DLNA.ORG_FLAGS=8d700000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "video/vnd.dlna.mpeg-tts", "additionalInfo": "DLNA.ORG_PN=MPEG_TS_SD_50_AC3_T;DLNA.ORG_FLAGS=8d700000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "video/vnd.dlna.mpeg-tts", "additionalInfo": "DLNA.ORG_PN=MPEG_TS_SD_60_AC3_T;DLNA.ORG_FLAGS=8d700000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "video/mpeg", "additionalInfo": "DLNA.ORG_PN=MPEG_TS_HD_50_L2_ISO;SONY.COM_PN=HD2_50_ISO;DLNA.ORG_FLAGS=8d700000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "video/mpeg", "additionalInfo": "DLNA.ORG_PN=MPEG_TS_HD_60_L2_ISO;SONY.COM_PN=HD2_60_ISO;DLNA.ORG_FLAGS=8d700000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "video/vnd.dlna.mpeg-tts", "additionalInfo": "DLNA.ORG_PN=MPEG_TS_HD_50_L2_T;SONY.COM_PN=HD2_50_T;DLNA.ORG_FLAGS=8d700000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "video/vnd.dlna.mpeg-tts", "additionalInfo": "DLNA.ORG_PN=MPEG_TS_HD_60_L2_T;SONY.COM_PN=HD2_60_T;DLNA.ORG_FLAGS=8d700000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "video/mpeg", "additionalInfo": "DLNA.ORG_PN=AVC_TS_HD_50_AC3_ISO;SONY.COM_PN=AVC_TS_HD_50_AC3_ISO;DLNA.ORG_FLAGS=8d700000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "video/mpeg", "additionalInfo": "DLNA.ORG_PN=AVC_TS_HD_60_AC3_ISO;SONY.COM_PN=AVC_TS_HD_60_AC3_ISO;DLNA.ORG_FLAGS=8d700000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "video/vnd.dlna.mpeg-tts", "additionalInfo": "DLNA.ORG_PN=AVC_TS_HD_50_AC3;SONY.COM_PN=AVC_TS_HD_50_AC3;DLNA.ORG_FLAGS=8d700000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "video/vnd.dlna.mpeg-tts", "additionalInfo": "DLNA.ORG_PN=AVC_TS_HD_60_AC3;SONY.COM_PN=AVC_TS_HD_60_AC3;DLNA.ORG_FLAGS=8d700000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "video/vnd.dlna.mpeg-tts", "additionalInfo": "DLNA.ORG_PN=AVC_TS_HD_50_AC3_T;SONY.COM_PN=AVC_TS_HD_50_AC3_T;DLNA.ORG_FLAGS=8d700000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "video/vnd.dlna.mpeg-tts", "additionalInfo": "DLNA.ORG_PN=AVC_TS_HD_60_AC3_T;SONY.COM_PN=AVC_TS_HD_60_AC3_T;DLNA.ORG_FLAGS=8d700000000000000000000000000000"},
      { "protocol": "http-get", "network": "*", "contentFormat": "video/x-mp2t-mphl-188", "additionalInfo": "*"}
    ]

**Comment by thibauts** [comment]
Thank you. What kind of file / MIME type are you trying to play ?

**Comment by thibauts** [comment]
Looks like you were trying to play a file not supported by your TV. Without further feedback I close the issue.
