### ISSUE TITLE
ssdp client

### ISSUE THREAD

**Issue by gyzerok** [thibauts/node-upnp-mediarenderer-client#12]
Can you suggest an ssdp client to use with your module? Or mb some working examples of how you using your module?

**Comment by thibauts** [comment]
I'm not really satisfied with available SSDP modules, but this should do the trick https://github.com/diversario/node-ssdp.

You're going to search for `urn:schemas-upnp-org:device:MediaRenderer:1`.

I'll try to post example code in the coming days.

**Comment by gyzerok** [comment]
@thibauts thank you for your reply. Node-ssdp is too solid and complex. Looking forward for better and lightweight ssdp client compatible with this module from you!

**Comment by kennylbj** [comment]
Try this https://github.com/manrueda/renderer-finder
