### ISSUE TITLE
TypeError: client.on is not a function

### ISSUE THREAD

**Issue by vitalets** [thibauts/node-upnp-mediarenderer-client#26]
Got this error when running example from readme...

**Comment by thibauts** [comment]
Please post the exact code you ran here. I'll look into it

**Comment by vitalets** [comment]
```js
var MediaRendererClient = require('upnp-mediarenderer-client');
var client = new MediaRendererClient('http://192.168.1.50:4873/foo.xml');
console.log(client.on)
```
outputs `undefined`

**Comment by vitalets** [comment]
I got the reason. I was using old version of package.

**Comment by thibauts** [comment]
;) OK

**Comment by vitalets** [comment]
BTW, @thibauts could you point the direction how to stream video from website (e.g. youtube or vimeo) on TV via mediarenderer-client ?
