### ISSUE TITLE
Support for subtitles through DLNA headers

### ISSUE THREAD

**Issue by thibauts** [thibauts/node-upnp-mediarenderer-client#5]

**Comment by SchizoDuckie** [comment]
https://git.popcorntime.io/stash/projects/MIR/repos/dlna-js/browse/examples/stream.js

**Comment by thibauts** [comment]
What are you suggesting exactly ?

**Comment by SchizoDuckie** [comment]
It looks like their example has subtitle headers working :)

**Comment by thibauts** [comment]
Their example is my example, check my gists.

This module doesn't implement the server part and it's on purpose.

**Comment by SchizoDuckie** [comment]
My apologies then :)

**Comment by thibauts** [comment]
No problem.

**Comment by thibauts** [comment]
For DLNA subtitles see here https://gist.github.com/thibauts/5f5f8d8ce6566c8289e6
