### ISSUE TITLE
Upnp Error  Resource not found (716)

### ISSUE THREAD

**Issue by wallydz** [thibauts/node-upnp-mediarenderer-client#8]
{ [Error: Resource not found (716)] code: 'EUPNP', statusCode: 500, errorCode: '716' }
Trace
    at /Users/wally/po/dlna/node-upnp-mediarenderer-client/test.js:18:9
    at /Users/wally/po/dlna/node-upnp-mediarenderer-client/index.js:46:22
    at IncomingMessage.<anonymous> (/Users/wally/po/dlna/node-upnp-mediarenderer-client/node_modules/upnp-device-client/index.js:132:18)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)

/Users/wally/po/dlna/node-upnp-mediarenderer-client/test.js:19
throw err;  
      ^
Error: Resource not found (716)
    at IncomingMessage.<anonymous> (/Users/wally/po/dlna/node-upnp-mediarenderer-client/node_modules/upnp-device-client/index.js:128:21)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)

**Comment by jaruba** [comment]
I'm trying to use ``node-upnp-mediarenderer-client`` with a Samsung Smart TV too, I got my device description url with ``node-ssdp``, it looks like this:

https://gist.github.com/jaruba/72af14e70e7cd2b47ed8

(it's very similar to the one @wallydz pasted in [this post](https://github.com/thibauts/node-upnp-mediarenderer-client/issues/7))

I'm also getting this error:

    Uncaught Error: Resource not found (716)

My test code:

    var MediaRendererClient = require('upnp-mediarenderer-client');

    var client = new MediaRendererClient('http://192.168.1.100:7676/smp_20_');

    var options = { 
        autoplay: true,
        contentType: 'video/mp4',
        metadata: {
            title: 'Some Movie Title',
            creator: 'John Doe',
            type: 'video' // can be 'video', 'audio' or 'image'
        }
    };

    client.load('http://commondatastorage.googleapis.com/gtv-videos-bucket/big_buck_bunny_1080p.mp4', options, function(err, result) {
        if(err) throw err;
        console.log('playing ...');
    });

Can I only stream local videos by creating a local http server with custom headers? I've had no luck yet while testing the code in this post..

**Comment by thibauts** [comment]
Most probably, yes. I've had no luck either streaming remote video (on a Sony Bravia). Please try with a local server and post feedback here.

**Comment by jaruba** [comment]
Works flawlessly with a local server. You've done some amazing work! :)
